-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cs_comments (
  cst_c_comment_page_id INT NOT NULL,
  cst_c_assoc_page_id INT NOT NULL,
  cst_c_comment_title TEXT NOT NULL,
  cst_c_block_name TEXT DEFAULT NULL,
  PRIMARY KEY(cst_c_comment_page_id)
);
