-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_comments (
  cst_c_comment_page_id INTEGER UNSIGNED NOT NULL,
  cst_c_assoc_page_id INTEGER UNSIGNED NOT NULL,
  cst_c_comment_title BLOB NOT NULL,
  cst_c_block_name BLOB DEFAULT NULL,
  PRIMARY KEY(cst_c_comment_page_id)
);
