-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_replies.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_replies (
  cst_r_reply_page_id INTEGER UNSIGNED NOT NULL,
  cst_r_comment_page_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(cst_r_reply_page_id)
);
