-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_watchlist.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_watchlist (
  cst_wl_page_id INTEGER UNSIGNED NOT NULL,
  cst_wl_user_id INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX cst_wl_index ON /*_*/cs_watchlist (cst_wl_page_id, cst_wl_user_id);
