-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_votes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cs_votes (
  cst_v_comment_id INT UNSIGNED NOT NULL,
  cst_v_user_id INT UNSIGNED NOT NULL,
  cst_v_vote TINYINT NOT NULL,
  UNIQUE INDEX cst_v_index (cst_v_comment_id, cst_v_user_id)
) /*$wgDBTableOptions*/;
